# Generated by Django 3.0.1 on 2020-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=64)),
                ('rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
