# Generated by Django 3.0.1 on 2020-10-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Player',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='name',
        ),
    ]
