# Generated by Django 3.0.1 on 2020-10-05 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201005_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.AddField(
            model_name='player',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='player registeded'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_total_rate', models.IntegerField(default=0)),
                ('team2_total_rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='team created')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
    ]
